/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.tuvarna.geo.models

import io.kotest.core.spec.style.ShouldSpec

class UserDTOTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of UserDTO
    // val modelInstance = UserDTO()

    // to test the property `username`
    should("test username") {
      // uncomment below to test the property
      // modelInstance.username shouldBe ("TODO")
    }

    // to test the property `email`
    should("test email") {
      // uncomment below to test the property
      // modelInstance.email shouldBe ("TODO")
    }

    // to test the property `password`
    should("test password") {
      // uncomment below to test the property
      // modelInstance.password shouldBe ("TODO")
    }

    // to test the property `usertype`
    should("test usertype") {
      // uncomment below to test the property
      // modelInstance.usertype shouldBe ("TODO")
    }

    // to test the property `isblocked`
    should("test isblocked") {
      // uncomment below to test the property
      // modelInstance.isblocked shouldBe ("TODO")
    }
  }
}
