/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tuvarna.geo.rest_api.models.LoggerDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseListLoggerDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseVoid

import com.squareup.moshi.Json

import com.tuvarna.geo.rest_api.infrastructure.ApiClient
import com.tuvarna.geo.rest_api.infrastructure.ApiResponse
import com.tuvarna.geo.rest_api.infrastructure.ClientException
import com.tuvarna.geo.rest_api.infrastructure.ClientError
import com.tuvarna.geo.rest_api.infrastructure.ServerException
import com.tuvarna.geo.rest_api.infrastructure.ServerError
import com.tuvarna.geo.rest_api.infrastructure.MultiValueMap
import com.tuvarna.geo.rest_api.infrastructure.PartConfig
import com.tuvarna.geo.rest_api.infrastructure.RequestConfig
import com.tuvarna.geo.rest_api.infrastructure.RequestMethod
import com.tuvarna.geo.rest_api.infrastructure.ResponseType
import com.tuvarna.geo.rest_api.infrastructure.Success
import com.tuvarna.geo.rest_api.infrastructure.toMultiValue

class AdminControllerApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080/api.tuvarna.geo.com/v1")
        }
    }

    /**
     * Block user
     * 
     * @param email 
     * @param blocked 
     * @return RestApiResponseVoid
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun blockUser(email: kotlin.String, blocked: kotlin.Boolean) : RestApiResponseVoid {
        val localVarResponse = blockUserWithHttpInfo(email = email, blocked = blocked)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RestApiResponseVoid
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Block user
     * 
     * @param email 
     * @param blocked 
     * @return ApiResponse<RestApiResponseVoid?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun blockUserWithHttpInfo(email: kotlin.String, blocked: kotlin.Boolean) : ApiResponse<RestApiResponseVoid?> {
        val localVariableConfig = blockUserRequestConfig(email = email, blocked = blocked)

        return request<Unit, RestApiResponseVoid>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation blockUser
     *
     * @param email 
     * @param blocked 
     * @return RequestConfig
     */
    fun blockUserRequestConfig(email: kotlin.String, blocked: kotlin.Boolean) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/admin/users/{email}/block/{blocked}".replace("{"+"email"+"}", encodeURIComponent(email.toString())).replace("{"+"blocked"+"}", encodeURIComponent(blocked.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Retrieve user logs
     * 
     * @return RestApiResponseListLoggerDTO
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getLogs() : RestApiResponseListLoggerDTO {
        val localVarResponse = getLogsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RestApiResponseListLoggerDTO
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve user logs
     * 
     * @return ApiResponse<RestApiResponseListLoggerDTO?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getLogsWithHttpInfo() : ApiResponse<RestApiResponseListLoggerDTO?> {
        val localVariableConfig = getLogsRequestConfig()

        return request<Unit, RestApiResponseListLoggerDTO>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getLogs
     *
     * @return RequestConfig
     */
    fun getLogsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/admin/fetch/logs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Save log
     * 
     * @param loggerDTO 
     * @return RestApiResponseVoid
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun saveLog(loggerDTO: LoggerDTO) : RestApiResponseVoid {
        val localVarResponse = saveLogWithHttpInfo(loggerDTO = loggerDTO)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RestApiResponseVoid
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Save log
     * 
     * @param loggerDTO 
     * @return ApiResponse<RestApiResponseVoid?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun saveLogWithHttpInfo(loggerDTO: LoggerDTO) : ApiResponse<RestApiResponseVoid?> {
        val localVariableConfig = saveLogRequestConfig(loggerDTO = loggerDTO)

        return request<LoggerDTO, RestApiResponseVoid>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation saveLog
     *
     * @param loggerDTO 
     * @return RequestConfig
     */
    fun saveLogRequestConfig(loggerDTO: LoggerDTO) : RequestConfig<LoggerDTO> {
        val localVariableBody = loggerDTO
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/admin/save/log",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
