/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tuvarna.geo.rest_api.models.DangerDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseEarthquake
import com.tuvarna.geo.rest_api.models.RestApiResponseSoil

import com.squareup.moshi.Json

import com.tuvarna.geo.rest_api.infrastructure.ApiClient
import com.tuvarna.geo.rest_api.infrastructure.ApiResponse
import com.tuvarna.geo.rest_api.infrastructure.ClientException
import com.tuvarna.geo.rest_api.infrastructure.ClientError
import com.tuvarna.geo.rest_api.infrastructure.ServerException
import com.tuvarna.geo.rest_api.infrastructure.ServerError
import com.tuvarna.geo.rest_api.infrastructure.MultiValueMap
import com.tuvarna.geo.rest_api.infrastructure.PartConfig
import com.tuvarna.geo.rest_api.infrastructure.RequestConfig
import com.tuvarna.geo.rest_api.infrastructure.RequestMethod
import com.tuvarna.geo.rest_api.infrastructure.ResponseType
import com.tuvarna.geo.rest_api.infrastructure.Success
import com.tuvarna.geo.rest_api.infrastructure.toMultiValue

class DangerControllerApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080/api.tuvarna.geo.com/v1")
        }
    }

    /**
     * Retrieve earthquake
     * 
     * @param dangerDTO 
     * @return RestApiResponseEarthquake
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getEarthquake(dangerDTO: DangerDTO) : RestApiResponseEarthquake {
        val localVarResponse = getEarthquakeWithHttpInfo(dangerDTO = dangerDTO)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RestApiResponseEarthquake
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve earthquake
     * 
     * @param dangerDTO 
     * @return ApiResponse<RestApiResponseEarthquake?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getEarthquakeWithHttpInfo(dangerDTO: DangerDTO) : ApiResponse<RestApiResponseEarthquake?> {
        val localVariableConfig = getEarthquakeRequestConfig(dangerDTO = dangerDTO)

        return request<DangerDTO, RestApiResponseEarthquake>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getEarthquake
     *
     * @param dangerDTO 
     * @return RequestConfig
     */
    fun getEarthquakeRequestConfig(dangerDTO: DangerDTO) : RequestConfig<DangerDTO> {
        val localVariableBody = dangerDTO
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/danger/earthquake",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Retrieve soil type
     * 
     * @param dangerDTO 
     * @return RestApiResponseSoil
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSoil(dangerDTO: DangerDTO) : RestApiResponseSoil {
        val localVarResponse = getSoilWithHttpInfo(dangerDTO = dangerDTO)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RestApiResponseSoil
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve soil type
     * 
     * @param dangerDTO 
     * @return ApiResponse<RestApiResponseSoil?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSoilWithHttpInfo(dangerDTO: DangerDTO) : ApiResponse<RestApiResponseSoil?> {
        val localVariableConfig = getSoilRequestConfig(dangerDTO = dangerDTO)

        return request<DangerDTO, RestApiResponseSoil>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSoil
     *
     * @param dangerDTO 
     * @return RequestConfig
     */
    fun getSoilRequestConfig(dangerDTO: DangerDTO) : RequestConfig<DangerDTO> {
        val localVariableBody = dangerDTO
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/danger/soil",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
