/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.apis


import io.kotest.core.spec.style.ShouldSpec

class AuthControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthControllerApi
        //val apiInstance = AuthControllerApi()

        // to test create
        should("test create") {
            // uncomment below to test create
            //val registerUserDTO : RegisterUserDTO =  // RegisterUserDTO |
            //val result : RestApiResponseVoid = apiInstance.create(registerUserDTO)
            //result shouldBe ("TODO")
        }

        // to test login
        should("test login") {
            // uncomment below to test login
            //val loginUserDTO : LoginUserDTO =  // LoginUserDTO |
            //val result : RestApiResponseLoggedInUserDTO = apiInstance.login(loginUserDTO)
            //result shouldBe ("TODO")
        }

    }
}
