/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.apis.RiskControllerApi
import com.tuvarna.geo.controller.models.RestApiResponseEarthquake
import com.tuvarna.geo.controller.models.RestApiResponseSoil
import com.tuvarna.geo.controller.models.RiskDTO

class RiskControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RiskControllerApi
        //val apiInstance = RiskControllerApi()

        // to test getEarthquake
        should("test getEarthquake") {
            // uncomment below to test getEarthquake
            //val riskDTO : RiskDTO =  // RiskDTO |
            //val result : RestApiResponseEarthquake = apiInstance.getEarthquake(riskDTO)
            //result shouldBe ("TODO")
        }

        // to test getSoil
        should("test getSoil") {
            // uncomment below to test getSoil
            //val riskDTO : RiskDTO =  // RiskDTO |
            //val result : RestApiResponseSoil = apiInstance.getSoil(riskDTO)
            //result shouldBe ("TODO")
        }

    }
}
