/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.tuvarna.geo.controller.models

import io.kotest.core.spec.style.ShouldSpec

class CoordinateTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of Coordinate
    // val modelInstance = Coordinate()

    // to test the property `x`
    should("test x") {
      // uncomment below to test the property
      // modelInstance.x shouldBe ("TODO")
    }

    // to test the property `y`
    should("test y") {
      // uncomment below to test the property
      // modelInstance.y shouldBe ("TODO")
    }

    // to test the property `z`
    should("test z") {
      // uncomment below to test the property
      // modelInstance.z shouldBe ("TODO")
    }

    // to test the property `valid`
    should("test valid") {
      // uncomment below to test the property
      // modelInstance.valid shouldBe ("TODO")
    }

    // to test the property `coordinate`
    should("test coordinate") {
      // uncomment below to test the property
      // modelInstance.coordinate shouldBe ("TODO")
    }

    // to test the property `m`
    should("test m") {
      // uncomment below to test the property
      // modelInstance.m shouldBe ("TODO")
    }
  }
}
