/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.tuvarna.geo.controller.models

import io.kotest.core.spec.style.ShouldSpec

class CoordinateSequenceTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CoordinateSequence
    // val modelInstance = CoordinateSequence()

    // to test the property `measures`
    should("test measures") {
      // uncomment below to test the property
      // modelInstance.measures shouldBe ("TODO")
    }

    // to test the property `dimension`
    should("test dimension") {
      // uncomment below to test the property
      // modelInstance.dimension shouldBe ("TODO")
    }
  }
}
