/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.models.GeometryFactory
import com.tuvarna.geo.controller.models.PrecisionModel

class GeometryFactoryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GeometryFactory
        //val modelInstance = GeometryFactory()

        // to test the property `precisionModel`
        should("test precisionModel") {
            // uncomment below to test the property
            //modelInstance.precisionModel shouldBe ("TODO")
        }

        // to test the property `coordinateSequenceFactory`
        should("test coordinateSequenceFactory") {
            // uncomment below to test the property
            //modelInstance.coordinateSequenceFactory shouldBe ("TODO")
        }

        // to test the property `srid`
        should("test srid") {
            // uncomment below to test the property
            //modelInstance.srid shouldBe ("TODO")
        }

    }
}
