/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.models.LoggerDTO

class LoggerDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoggerDTO
        //val modelInstance = LoggerDTO()

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property `ip`
        should("test ip") {
            // uncomment below to test the property
            //modelInstance.ip shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
