/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.tuvarna.geo.controller.models

import io.kotest.core.spec.style.ShouldSpec

class LoginUserDTOTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of LoginUserDTO
    // val modelInstance = LoginUserDTO()

    // to test the property `email`
    should("test email") {
      // uncomment below to test the property
      // modelInstance.email shouldBe ("TODO")
    }

    // to test the property `password`
    should("test password") {
      // uncomment below to test the property
      // modelInstance.password shouldBe ("TODO")
    }
  }
}
