/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.models.PrecisionModel

class PrecisionModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PrecisionModel
        //val modelInstance = PrecisionModel()

        // to test the property `scale`
        should("test scale") {
            // uncomment below to test the property
            //modelInstance.scale shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `floating`
        should("test floating") {
            // uncomment below to test the property
            //modelInstance.floating shouldBe ("TODO")
        }

        // to test the property `maximumSignificantDigits`
        should("test maximumSignificantDigits") {
            // uncomment below to test the property
            //modelInstance.maximumSignificantDigits shouldBe ("TODO")
        }

        // to test the property `offsetX`
        should("test offsetX") {
            // uncomment below to test the property
            //modelInstance.offsetX shouldBe ("TODO")
        }

        // to test the property `offsetY`
        should("test offsetY") {
            // uncomment below to test the property
            //modelInstance.offsetY shouldBe ("TODO")
        }

    }
}
