/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.models.Soil
import com.tuvarna.geo.controller.models.MultiPolygon

class SoilTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Soil
        //val modelInstance = Soil()

        // to test the property `gid`
        should("test gid") {
            // uncomment below to test the property
            //modelInstance.gid shouldBe ("TODO")
        }

        // to test the property `snum`
        should("test snum") {
            // uncomment below to test the property
            //modelInstance.snum shouldBe ("TODO")
        }

        // to test the property `faosoil`
        should("test faosoil") {
            // uncomment below to test the property
            //modelInstance.faosoil shouldBe ("TODO")
        }

        // to test the property `domsoi`
        should("test domsoi") {
            // uncomment below to test the property
            //modelInstance.domsoi shouldBe ("TODO")
        }

        // to test the property `phase1`
        should("test phase1") {
            // uncomment below to test the property
            //modelInstance.phase1 shouldBe ("TODO")
        }

        // to test the property `phase2`
        should("test phase2") {
            // uncomment below to test the property
            //modelInstance.phase2 shouldBe ("TODO")
        }

        // to test the property `misclu1`
        should("test misclu1") {
            // uncomment below to test the property
            //modelInstance.misclu1 shouldBe ("TODO")
        }

        // to test the property `misclu2`
        should("test misclu2") {
            // uncomment below to test the property
            //modelInstance.misclu2 shouldBe ("TODO")
        }

        // to test the property `permafrost`
        should("test permafrost") {
            // uncomment below to test the property
            //modelInstance.permafrost shouldBe ("TODO")
        }

        // to test the property `cntcode`
        should("test cntcode") {
            // uncomment below to test the property
            //modelInstance.cntcode shouldBe ("TODO")
        }

        // to test the property `cntname`
        should("test cntname") {
            // uncomment below to test the property
            //modelInstance.cntname shouldBe ("TODO")
        }

        // to test the property `sqkm`
        should("test sqkm") {
            // uncomment below to test the property
            //modelInstance.sqkm shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `geom`
        should("test geom") {
            // uncomment below to test the property
            //modelInstance.geom shouldBe ("TODO")
        }

    }
}
