/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.controller.models.UserInfoDTO

class UserInfoDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserInfoDTO
        //val modelInstance = UserInfoDTO()

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `isblocked`
        should("test isblocked") {
            // uncomment below to test the property
            //modelInstance.isblocked shouldBe ("TODO")
        }

        // to test the property `userType`
        should("test userType") {
            // uncomment below to test the property
            //modelInstance.userType shouldBe ("TODO")
        }

    }
}
