/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param x 
 * @param y 
 * @param z 
 * @param valid 
 * @param coordinate 
 * @param m 
 */


data class Coordinate (

    @Json(name = "x")
    val x: kotlin.Double? = null,

    @Json(name = "y")
    val y: kotlin.Double? = null,

    @Json(name = "z")
    val z: kotlin.Double? = null,

    @Json(name = "valid")
    val valid: kotlin.Boolean? = null,

    @Json(name = "coordinate")
    val coordinate: Coordinate? = null,

    @Json(name = "m")
    val m: kotlin.Double? = null

)

