/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.models

import com.tuvarna.geo.rest_api.models.MultiPolygon

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param geom 
 * @param dn 
 */


data class Earthquake (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "geom")
    val geom: MultiPolygon? = null,

    @Json(name = "dn")
    val dn: kotlin.Int? = null

)

