/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param measures
 * @param dimension
 */


data class CoordinateSequence (

    @Json(name = "measures")
    val measures: kotlin.Int? = null,

    @Json(name = "dimension")
    val dimension: kotlin.Int? = null

)

