/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.controller.models

import com.tuvarna.geo.controller.models.MultiPolygon

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param gid
 * @param snum
 * @param faosoil
 * @param domsoi
 * @param phase1
 * @param phase2
 * @param misclu1
 * @param misclu2
 * @param permafrost
 * @param cntcode
 * @param cntname
 * @param sqkm
 * @param country
 * @param geom
 */


data class Soil (

    @Json(name = "gid")
    val gid: kotlin.Int? = null,

    @Json(name = "snum")
    val snum: kotlin.Float? = null,

    @Json(name = "faosoil")
    val faosoil: kotlin.String? = null,

    @Json(name = "domsoi")
    val domsoi: kotlin.String? = null,

    @Json(name = "phase1")
    val phase1: kotlin.String? = null,

    @Json(name = "phase2")
    val phase2: kotlin.String? = null,

    @Json(name = "misclu1")
    val misclu1: kotlin.String? = null,

    @Json(name = "misclu2")
    val misclu2: kotlin.String? = null,

    @Json(name = "permafrost")
    val permafrost: kotlin.String? = null,

    @Json(name = "cntcode")
    val cntcode: kotlin.Double? = null,

    @Json(name = "cntname")
    val cntname: kotlin.String? = null,

    @Json(name = "sqkm")
    val sqkm: kotlin.Double? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "geom")
    val geom: MultiPolygon? = null

)

