/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.tuvarna.geo.apis

import io.kotest.core.spec.style.ShouldSpec

class RegisterControllerApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RegisterControllerApi
    // val apiInstance = RegisterControllerApi()

    // to test create
    should("test create") {
      // uncomment below to test create
      // val userDTO : UserDTO =  // UserDTO |
      // val result : kotlin.String = apiInstance.create(userDTO)
      // result shouldBe ("TODO")
    }
  }
}
