/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.rest_api.apis.AdminControllerApi
import com.tuvarna.geo.rest_api.models.LoggerDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseListLoggerDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseListUserInfoDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseVoid

class AdminControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminControllerApi
        //val apiInstance = AdminControllerApi()

        // to test blockUser
        should("test blockUser") {
            // uncomment below to test blockUser
            //val email : kotlin.String = email_example // kotlin.String | 
            //val blocked : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : RestApiResponseVoid = apiInstance.blockUser(email, blocked)
            //result shouldBe ("TODO")
        }

        // to test getLogs
        should("test getLogs") {
            // uncomment below to test getLogs
            //val userType : kotlin.String = userType_example // kotlin.String | 
            //val result : RestApiResponseListLoggerDTO = apiInstance.getLogs(userType)
            //result shouldBe ("TODO")
        }

        // to test getUsers
        should("test getUsers") {
            // uncomment below to test getUsers
            //val userType : kotlin.String = userType_example // kotlin.String | 
            //val result : RestApiResponseListUserInfoDTO = apiInstance.getUsers(userType)
            //result shouldBe ("TODO")
        }

        // to test promoteUser
        should("test promoteUser") {
            // uncomment below to test promoteUser
            //val email : kotlin.String = email_example // kotlin.String | 
            //val userType : kotlin.String = userType_example // kotlin.String | 
            //val result : RestApiResponseVoid = apiInstance.promoteUser(email, userType)
            //result shouldBe ("TODO")
        }

        // to test saveLog
        should("test saveLog") {
            // uncomment below to test saveLog
            //val userType : kotlin.String = userType_example // kotlin.String | 
            //val loggerDTO : LoggerDTO =  // LoggerDTO | 
            //val result : RestApiResponseVoid = apiInstance.saveLog(userType, loggerDTO)
            //result shouldBe ("TODO")
        }

    }
}
