/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.rest_api.apis.AuthControllerApi
import com.tuvarna.geo.rest_api.models.LoginUserDTO
import com.tuvarna.geo.rest_api.models.RegisterUserDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseLoggedInUserDTO
import com.tuvarna.geo.rest_api.models.RestApiResponseVoid

class AuthControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthControllerApi
        //val apiInstance = AuthControllerApi()

        // to test create
        should("test create") {
            // uncomment below to test create
            //val registerUserDTO : RegisterUserDTO =  // RegisterUserDTO | 
            //val result : RestApiResponseVoid = apiInstance.create(registerUserDTO)
            //result shouldBe ("TODO")
        }

        // to test login
        should("test login") {
            // uncomment below to test login
            //val loginUserDTO : LoginUserDTO =  // LoginUserDTO | 
            //val result : RestApiResponseLoggedInUserDTO = apiInstance.login(loginUserDTO)
            //result shouldBe ("TODO")
        }

    }
}
