package com.tuvarna.geo.config

data class SoilTypesDTO(
    val Ao: String = "Orthic Acrisols",
    val Af: String = "Ferric Acrisols",
    val Ah: String = "Humic Acrisols",
    val Ap: String = "Plinthic Acrisols",
    val Ag: String = "Gleyic Acrisols",

    val Be: String = "Eutric Cambisols",
    val Bd: String = "Dystric Cambisols",
    val Bh: String = "Humic Cambisols",
    val Bg: String = "Gleyic Cambisols",
    val Bx: String = "Gelic Cambisols",
    val Bk: String = "Calcic Cambisols",
    val Bc: String = "Chromic Cambisols",
    val Bv: String = "Vertic Cambisols",
    val Bf: String = "Ferralic Cambisols",

    val Ch: String = "Haplic Chernozems",
    val Ck: String = "Calcic Chernozems",
    val Cl: String = "Luvic Chernozems",
    val Cg: String = "Glossic Chernozems",

    val De: String = "Eutric Podzoluvisols",
    val Dd: String = "Dystric Podzoluvisols",
    val Dg: String = "Gleyic Podzoluvisols",

    val Fo: String = "Orthic Ferralsols",
    val Fx: String = "Xanthic Ferralsols",
    val Fr: String = "Rhodic Ferralsols",
    val Fh: String = "Humic Ferralsols",
    val Fa: String = "Acric Ferralsols",
    val Fp: String = "Plinthic Ferralsols",

    val Ge: String = "Eutric Gleysols",
    val Gc: String = "Calcaric Gleysols",
    val Gd: String = "Dystric Gleysols",
    val Gm: String = "Mollic Gleysols",
    val Gh: String = "Humic Gleysols",
    val Gp: String = "Plinthic Gleysols",
    val Gx: String = "Gelic Gleysols",

    val Hh: String = "Haplic Phaeozems",
    val Hc: String = "Calcaric Phaeozems",
    val Hl: String = "Luvic Phaeozems",
    val Hg: String = "Gleyic Phaeozems",

    val Je: String = "Eutric Fluvisols",
    val Jc: String = "Calcaric Fluvisols",
    val Jd: String = "Dystric Fluvisols",
    val Jt: String = "Thionic Fluvisols",

    val Kh: String = "Haplic Kastanozems",
    val Kk: String = "Calcic Kastanozems",
    val Kl: String = "Luvic Kastanozems",

    val Lo: String = "Orthic Luvisols",
    val Lc: String = "Chromic Luvisols",
    val Lk: String = "Calcic Luvisols",
    val Lv: String = "Vertic Luvisols",
    val Lf: String = "Ferric Luvisols",
    val La: String = "Albic Luvisols",
    val Lp: String = "Plinthic Luvisols",
    val Lg: String = "Gleyic Luvisols",

    val Mo: String = "Orthic Greyzems",
    val Mg: String = "Gleyic Greyzems",

    val Ne: String = "Eutric Nitosols",
    val Nd: String = "Dystric Nitosols",
    val Nh: String = "Humic Nitosols",

    val Oe: String = "Eutric Histosols",
    val Od: String = "Dystric Histosols",
    val Ox: String = "Gelic Histosols",

    val Po: String = "Orthic Podzols",
    val Pl: String = "Leptic Podzols",
    val Pf: String = "Ferric Podzols",
    val Ph: String = "Humic Podzols",
    val Pp: String = "Placic Podzols",
    val Pg: String = "Gleyic Podzols",

    val Qc: String = "Cambic Arenosols",
    val Ql: String = "Luvic Arenosols",
    val Qf: String = "Ferralic Arenosols",
    val Qa: String = "Albic Arenosols",

    val Re: String = "Eutric Gleysols",
    val Rc: String = "Calcaric Regosols",
    val Rd: String = "Dystric Regosols",
    val Rx: String = "Gelic Regosols",

    val So: String = "Orthic Solonetz",
    val Sm: String = "Mollic Solonetz",
    val Sg: String = "Gleyic Solonetz",

    val To: String = "Ochric Andosols",
    val Tm: String = "Mollic Andosols",
    val Th: String = "Humic Andosols",
    val Tv: String = "Vitric Andosols",

    val Vp: String = "Pellic Vertisols",
    val Vc: String = "Chromic Vertisols",

    val We: String = "Eutric Planosols",
    val Wd: String = "Dystric Planosols",
    val Wm: String = "Mollic Planosols",
    val Wh: String = "Humic Planosols",
    val Ws: String = "Solodic Planosols",
    val Wx: String = "Gelic Planosols",

    val Xh: String = "Haplic Xerosols",
    val Xk: String = "Calcic Xerosols",
    val Xy: String = "Gypsic Xerosols",
    val Xl: String = "Luvic Xerosols",

    val Yh: String = "Haplic Yermosols",
    val Yk: String = "Calcic Yermosols",
    val Yy: String = "Gypsic Yermosols",
    val Yl: String = "Luvic Yermosols",
    val Yt: String = "Takyric Yermosols",

    val Zo: String = "Orthic Solonchaks",
    val Zm: String = "Mollic Solonchaks",
    val Zt: String = "Takyric Solonchaks",
    val Zg: String = "Gleyic Solonchaks",

    val DS: String = "Dunes or shifting sands",
    val ST: String = "Salt flats",
    val RK: String = "Rock debris or desert detritus",
    val WR: String = "Inland water or ocean",
    val GL: String = "Glacier",
    val ND: String = "No data",

    val A : String = "ACRISOLS",
    val B : String = "CAMBISOLS",
    val C : String = "CHERNOZEMS",
    val D : String = "PODZOLUVISOLS",
    val E: String = "RENDZINAS",
    val F : String = "FERRALSOLS",
    val G : String = "GLEYSOLS",
    val H : String = "PHAEOZEMS",
    val I: String = "LITHOSOLS",
    val J: String = "FLUVISOLS",
    val K: String = "KASTANOZEMS",
    val L: String = "LUVISOLS",
    val M: String = "GREYZEMS",
    val N: String = "NITOSOLS",
    val O: String = "HISTOSOLS",
    val P: String = "PODZOLS",
    val Q: String = "ARENOSOLS",
    val R: String = "REGOSOLS",
    val S: String = "SOLONETZ",
    val T: String = "ANDOSOLS",
    val U: String = "RANKERS",
    val V: String = "VERTISOLS",
    val W: String = "PLANOSOLS",
    val X: String = "XEROSOLS",
    val Y: String = "YERMOSOLS",
    val Z: String = "SOLONCHAKS"

)
