/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.rest_api.models.Earthquake
import com.tuvarna.geo.rest_api.models.MultiPolygon

class EarthquakeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Earthquake
        //val modelInstance = Earthquake()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `geom`
        should("test geom") {
            // uncomment below to test the property
            //modelInstance.geom shouldBe ("TODO")
        }

        // to test the property `dn`
        should("test dn") {
            // uncomment below to test the property
            //modelInstance.dn shouldBe ("TODO")
        }

    }
}
