/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.rest_api.models.Envelope

class EnvelopeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Envelope
        //val modelInstance = Envelope()

        // to test the property ``null``
        should("test `null`") {
            // uncomment below to test the property
            //modelInstance.`null` shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `diameter`
        should("test diameter") {
            // uncomment below to test the property
            //modelInstance.diameter shouldBe ("TODO")
        }

        // to test the property `minX`
        should("test minX") {
            // uncomment below to test the property
            //modelInstance.minX shouldBe ("TODO")
        }

        // to test the property `maxX`
        should("test maxX") {
            // uncomment below to test the property
            //modelInstance.maxX shouldBe ("TODO")
        }

        // to test the property `minY`
        should("test minY") {
            // uncomment below to test the property
            //modelInstance.minY shouldBe ("TODO")
        }

        // to test the property `maxY`
        should("test maxY") {
            // uncomment below to test the property
            //modelInstance.maxY shouldBe ("TODO")
        }

        // to test the property `area`
        should("test area") {
            // uncomment below to test the property
            //modelInstance.area shouldBe ("TODO")
        }

    }
}
