/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tuvarna.geo.rest_api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tuvarna.geo.rest_api.models.MultiPolygon
import com.tuvarna.geo.rest_api.models.Coordinate
import com.tuvarna.geo.rest_api.models.Envelope
import com.tuvarna.geo.rest_api.models.Geometry
import com.tuvarna.geo.rest_api.models.GeometryFactory
import com.tuvarna.geo.rest_api.models.Point
import com.tuvarna.geo.rest_api.models.PrecisionModel

class MultiPolygonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MultiPolygon
        //val modelInstance = MultiPolygon()

        // to test the property `envelope`
        should("test envelope") {
            // uncomment below to test the property
            //modelInstance.envelope shouldBe ("TODO")
        }

        // to test the property `factory`
        should("test factory") {
            // uncomment below to test the property
            //modelInstance.factory shouldBe ("TODO")
        }

        // to test the property `userData`
        should("test userData") {
            // uncomment below to test the property
            //modelInstance.userData shouldBe ("TODO")
        }

        // to test the property `boundaryDimension`
        should("test boundaryDimension") {
            // uncomment below to test the property
            //modelInstance.boundaryDimension shouldBe ("TODO")
        }

        // to test the property `geometryType`
        should("test geometryType") {
            // uncomment below to test the property
            //modelInstance.geometryType shouldBe ("TODO")
        }

        // to test the property `boundary`
        should("test boundary") {
            // uncomment below to test the property
            //modelInstance.boundary shouldBe ("TODO")
        }

        // to test the property `dimension`
        should("test dimension") {
            // uncomment below to test the property
            //modelInstance.dimension shouldBe ("TODO")
        }

        // to test the property `length`
        should("test length") {
            // uncomment below to test the property
            //modelInstance.length shouldBe ("TODO")
        }

        // to test the property `empty`
        should("test empty") {
            // uncomment below to test the property
            //modelInstance.empty shouldBe ("TODO")
        }

        // to test the property `coordinate`
        should("test coordinate") {
            // uncomment below to test the property
            //modelInstance.coordinate shouldBe ("TODO")
        }

        // to test the property `coordinates`
        should("test coordinates") {
            // uncomment below to test the property
            //modelInstance.coordinates shouldBe ("TODO")
        }

        // to test the property `numPoints`
        should("test numPoints") {
            // uncomment below to test the property
            //modelInstance.numPoints shouldBe ("TODO")
        }

        // to test the property `numGeometries`
        should("test numGeometries") {
            // uncomment below to test the property
            //modelInstance.numGeometries shouldBe ("TODO")
        }

        // to test the property `area`
        should("test area") {
            // uncomment below to test the property
            //modelInstance.area shouldBe ("TODO")
        }

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

        // to test the property `simple`
        should("test simple") {
            // uncomment below to test the property
            //modelInstance.simple shouldBe ("TODO")
        }

        // to test the property `envelopeInternal`
        should("test envelopeInternal") {
            // uncomment below to test the property
            //modelInstance.envelopeInternal shouldBe ("TODO")
        }

        // to test the property `srid`
        should("test srid") {
            // uncomment below to test the property
            //modelInstance.srid shouldBe ("TODO")
        }

        // to test the property `precisionModel`
        should("test precisionModel") {
            // uncomment below to test the property
            //modelInstance.precisionModel shouldBe ("TODO")
        }

        // to test the property `rectangle`
        should("test rectangle") {
            // uncomment below to test the property
            //modelInstance.rectangle shouldBe ("TODO")
        }

        // to test the property `centroid`
        should("test centroid") {
            // uncomment below to test the property
            //modelInstance.centroid shouldBe ("TODO")
        }

        // to test the property `interiorPoint`
        should("test interiorPoint") {
            // uncomment below to test the property
            //modelInstance.interiorPoint shouldBe ("TODO")
        }

    }
}
